name: stylesavvy
description: A fashion styling and shopping app

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  http: ^0.13.0
  cached_network_image: ^3.0.0
  video_player: ^2.1.0
  url_launcher: ^6.0.9
  table_calendar: ^3.0.9
  flutter_datetime_picker: ^1.4.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/Background.jpeg
  fonts:
    - family: MaterialIcons
      fonts:
        - asset: fonts/MaterialIcons-Regular.otf
